version: "3.3"

services:
  app:
    image: whisper:1.0.0
    volumes:
      - ./data:/app/data
      - ./tests:/app/tests
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
